services:
  speed-reading:
    image: ${REGISTRY_REPO:-speed-reading}:${VERSION:-latest}
    container_name: speed-reading
    ports:
      - "33090:80"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
    name: mynet
